### ISSUE TITLE
Ambiguous constructor when trying to inject CommandLineApplication

### ISSUE THREAD

**Issue by jasonla** [natemcmaster/CommandLineUtils#234]
**Describe the bug**
InvalidOperationException thrown when trying to inject CommandLineApplication
```
'McMaster.Extensions.CommandLineUtils.CommandLineApplication`1[Program]'. The following constructors are ambiguous:
Void .ctor(Boolean)
Void .ctor(McMaster.Extensions.CommandLineUtils.IConsole)
```

**To Reproduce**
I read the DI documentation, but I might be misunderstanding what's being said. `CommandLineApplication` is supposed to be a standard service that I can inject.

However, given this configuration:

``` 
 // setup service provider
	var serviceProvider = new ServiceCollection()
		.AddSingleton<IMyService, MyService>()
		.AddSingleton<IConsole>(PhysicalConsole.Singleton)
		.AddSingleton<CommandLineApplication<Program>>()
		.AddLogging(c => c.AddSerilog())
		.BuildServiceProvider();

	var app = new CommandLineApplication<Program>();
	app.Conventions
		.UseDefaultConventions()
		.UseConstructorInjection(serviceProvider);

	return app.Execute(args);
```
Am I incorrectly registering the instance of the `CommandLineApplication`?

MyService tries to get the instance of `CommandLineApplication` through constructor injection:

```
public class MyService : IMyService
{
	private readonly ILogger _logger;
	private readonly CommandLineApplication<Program> _commandLineApplication;


	public MyService(ILogger<MyService> logger,
		CommandLineApplication<Program> commandLineApplication
		)
	{
		_logger = logger;
		_commandLineApplication = commandLineApplication;
	}
}
```

**Exception log**
```System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Unable to activate type 'McMaster.Extensions.CommandLineUtils.CommandLineApplication`1[Program]'. The following constructors are ambiguous:
Void .ctor(Boolean)
Void .ctor(McMaster.Extensions.CommandLineUtils.IConsole)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ServiceProvider.GetService(Type serviceType)
   at McMaster.Extensions.CommandLineUtils.Conventions.ConstructorInjectionConvention.FindMatchedConstructor[TModel](ConstructorInfo[] constructors, IServiceProvider services, Boolean throwIfNoParameterTypeRegistered)
   at McMaster.Extensions.CommandLineUtils.Conventions.ConstructorInjectionConvention.ApplyImpl[TModel](ConventionContext context)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at McMaster.Extensions.CommandLineUtils.Conventions.ConstructorInjectionConvention.Apply(ConventionContext context)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Builder.McMaster.Extensions.CommandLineUtils.Conventions.IConventionBuilder.AddConvention(IConvention convention)```

**Comment by natemcmaster** [comment]
Try removing this line from your service configuration. It should be unnecessary.
```
.AddSingleton<CommandLineApplication<Program>>()
```

**Comment by jasonla** [comment]
Removing that line still results in an error, but it now seems like it can't find CommandLineApplication at all:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Unable to resolve service for type 'McMaster.Extensions.CommandLineUtils.CommandLineApplication`1[Program]' while attempting to activate 'MyService'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ServiceProvider.GetService(Type serviceType)
   at McMaster.Extensions.CommandLineUtils.Conventions.ConstructorInjectionConvention.FindMatchedConstructor[TModel](ConstructorInfo[] constructors, IServiceProvider services, Boolean throwIfNoParameterTypeRegistered)
   at McMaster.Extensions.CommandLineUtils.Conventions.ConstructorInjectionConvention.ApplyImpl[TModel](ConventionContext context)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at McMaster.Extensions.CommandLineUtils.Conventions.ConstructorInjectionConvention.Apply(ConventionContext context)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Builder.McMaster.Extensions.CommandLineUtils.Conventions.IConventionBuilder.AddConvention(IConvention convention)
```

**Comment by natemcmaster** [comment]
Ah, I see something I missed in your repro code. I don't think there is a service for CommandLineApp of T. Try the non-generic base type.

**Comment by jasonla** [comment]
Hrm... upon further inspection, this might be a chicken and egg problem. This is the constructor of Program class:

```
        public Program(IMyService myService)
        {
            _myService = myService;
        }
```

Removing `CommandLineApplication<Program>` from the `MyService` constructor seems to make things work. On second look, this might be better anyway since `IMyservice` doesn't really need the `CommandLineApplication`, generic or otherwise. All IMyService really needs are the values of the options passed in.

For posterity and anyone else looking at this later on, this is the completed refactor that works:

```csharp
using McMaster.Extensions.CommandLineUtils;
using McMaster.Extensions.CommandLineUtils.Abstractions;
using McMaster.Extensions.CommandLineUtils.HelpText;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Serilog;
using System;

namespace My.Console
{
    [HelpOption]
    public class Program
    {
        private readonly IMyService _myService;

        public static int Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
                .ReadFrom.Configuration(
                    new ConfigurationBuilder()
                    .AddJsonFile("appSettings.json")
                    .Build())
                .CreateLogger();

            try
            {
                // setup service provider
                var serviceProvider = new ServiceCollection()
                    .AddSingleton<IMyservice, MyService>()
                    .AddSingleton<IConsole>(PhysicalConsole.Singleton)
                    .AddLogging(c => c.AddSerilog())
                    .BuildServiceProvider();

                var app = new CommandLineApplication<Program>();
                app.Conventions
                    .UseDefaultConventions()
                    .UseConstructorInjection(serviceProvider);

                return app.Execute(args);
            }
            catch (Exception ex)
            {
                Log.Fatal(ex, "Program terminated unexpectedly.");
                return 1;
            }
        }

        public Program(IMyService myService)
        {
            _myService = myService;
        }

        private void OnExecute(CommandLineApplication<Program> commandLineApplication)
        {
            Log.Information("Performing work on service.");
            _myService.DoWork(commandLineApplication.Model.OptionFilename);
        }

        [Option("-f|--file <FILE>", "Filename of the json file.", CommandOptionType.SingleValue)]
        public string OptionFilename { get; set; }

    }

    public class MyService : IMyService
    {
        private readonly ILogger _logger;

        public MyService(ILogger<MyService> logger)
        {
            _logger = logger;
        }

        public void DoWork(string fileName)
        {
            /// do something
        }
    }
}
```

**Comment by jasonla** [comment]
I'm going to close the issue, but thank you so much for the help and the library, @natemcmaster.

**Comment by natemcmaster** [comment]
Happy to help!
