### ISSUE TITLE
NullReferenceException when calling HelloWorld.Attributes sample with -h or -? instead of --help

### ISSUE THREAD

**Issue by philippgille** [natemcmaster/CommandLineUtils#26]
Description
-----------

When running `dotnet .\bin\Debug\netcoreapp2.0\HelloWorld.Attributes.dll --help` I get the expected output:
```
Usage:  [options]

Options:
  -?|-h|--help            Show help information
  -s|--subject <SUBJECT>  The subject
```

But when running `dotnet .\bin\Debug\netcoreapp2.0\HelloWorld.Attributes.dll -h` I get an error:
```
Usage:  [options]

Options:
  -?|-h|--help            Show help information
  -s|--subject <SUBJECT>  The subject


Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Bind[TApp](IConsole console, String[] args) in X:\Path\To\CommandLineUtils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 150
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](IConsole console, String[] args) in X:\Path\To\CommandLineUtils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 48
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](String[] args) in X:\Path\To\CommandLineUtils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 31
   at Program.Main(String[] args) in X:\Path\To\CommandLineUtils\samples\HelloWorld.Attributes\Program.cs:line 11
```

Info
----

- Latest commit on `master` as of 2017-12-03T00:13:42Z, [1a843bd4db8d536e54f9d7ae9b58ebf53f16b521](https://github.com/natemcmaster/CommandLineUtils/tree/1a843bd4db8d536e54f9d7ae9b58ebf53f16b521), which is newer than the latest tag `v2.1.0-beta`
- Windows 10 Pro Fall Creators Update
- `dotnet --version`: `2.0.0`
- Executed in PowerShell in the Visual Studio Code integrated terminal

**Comment by philippgille** [comment]
I gave it a try in PR #27, but a couple of tests fail now. Let's discuss the solution in the PR comments.
