### ISSUE TITLE
Subcommands and dependency injection examples?

### ISSUE THREAD

**Issue by VictorioBerra** [natemcmaster/CommandLineUtils#269]
Im using the host builder extensions. Are there any examples on how I can use subcommands and inject resources into them just like I would normally?

**Comment by VictorioBerra** [comment]
I am unable to get any of the examples for subcommands working with dependency injection. For example, this is what happens when I try to use a sub command I get this:

```
[14:03:35 FTL]  Console Host terminated unexpectedly
System.InvalidOperationException: The constructor of type 'My.Console.Program+Test' contains the parameter of type 'My.Console.Greeter' is not registered, Ensure the type 'My..Console.Greeter' are registered in additional services with CommandLineApplication.Conventions.UseConstructorInjection(IServiceProvider additionalServices)
   at McMaster.Extensions.CommandLineUtils.Conventions.ConstructorInjectionConvention.<>c__DisplayClass6_2`1.<FindMatchedConstructor>b__3()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication`1.Dispose()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostBuilderExtensions.RunCommandLineApplicationAsync[TApp](IHostBuilder hostBuilder, String[] args, CancellationToken cancellationToken)
   at My..Console.Program.CreateHostBuilderAsync(String[] args) in C:\Source\EA\My..Console\src\My..Console\Program.cs:line 77
   at My..Console.Program.Main(String[] args) in C:\Source\EA\My..Console\src\My..Console\Program.cs:line 52
```

So it looks like the subcommand is not being instantiated the "generic host way"

**Comment by VictorioBerra** [comment]
[I found a possible solution. I see you inject IServiceProvider for me](https://natemcmaster.github.io/CommandLineUtils/docs/advanced/dependency-injection.html#using-the-standard-services), and with that I am able to manually resolve my service in my ctor with `GetService()`. 

This is pretty ugly compared to just asking for the service in my ctor. But this gets me unblocked. Is there some better way? Why cant sub commands be registered with DI container and then resolved from DI when needed?

**Comment by VictorioBerra** [comment]
My issue was im asking for Greeter and not IGreeter so it looks like this all works as expected. My bad.
