### ISSUE TITLE
Exception thrown when attempting to generate help text with custom IValidator present

### ISSUE THREAD

**Issue by adamsjdavid-work** [natemcmaster/CommandLineUtils#440]
When upgrading from V3.0 to V3.1, we experience test failures around the -h | --help flag. Namely, in our testing environment, running the help command is throwing an exception inside the McMaster Utility.

As part of our creation workflow, we have a custom implementation of IValidator called 'ExistingDirectoryOrTarFileValidator'. 

`private class ExistingDirectoryOrTarFileValidator : IValidator {[removed for brevity]}`

It is added to an IValidationBuilder with the .Use(IValidator) method.

`public static IValidationBuilder IfExistingFileThenHasTarExtension(this IValidationBuilder builder)
        {
            builder.Use(new ExistingDirectoryOrTarFileValidator());
            return builder;
        }`

This builder is used when creating a command option.

`var inputOption = app.Option<string>(
                    "-i|--input",
                    "A directory, or a *.tar archive, containing all source files to be compiled.",
                    CommandOptionType.MultipleValue)
                .IsRequired()
                .Accepts(p => p.ExistingFileOrDirectory()
                    .IfExistingFileThenHasTarExtension());`

`Unable to cast object of type 'ExistingDirectoryOrTarFileValidator' to type 'McMaster.Extensions.CommandLineUtils.Validation.AttributeValidator'.`

Stack trace:

`   at System.Linq.Enumerable.<CastIterator>d__63``1.MoveNext() in /_/src/System.Linq/src/System/Linq/Cast.cs:line 52
   at McMaster.Extensions.CommandLineUtils.HelpText.DefaultHelpTextGenerator.GenerateOptions(CommandLineApplication application, TextWriter output, IReadOnlyList``1 visibleOptions, Int32 firstColumnWidth)
   at McMaster.Extensions.CommandLineUtils.HelpText.DefaultHelpTextGenerator.GenerateBody(CommandLineApplication application, TextWriter output)
   at McMaster.Extensions.CommandLineUtils.HelpText.DefaultHelpTextGenerator.Generate(CommandLineApplication application, TextWriter output)
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessOption(OptionArgument arg)
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessNext()
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.Process()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Parse(String[] args)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<ExecuteAsync>d__157.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 180
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 151
   at System.Runtime.CompilerServices.TaskAwaiter``1.GetResult() in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 369
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at AX.TextLad.Compiler.CLI.Program.Main(String[] args) in D:\repos\[removed for privacy]\Program.cs:line 255`

This bug appears to have been introduced in #369.

**Comment by scott-xu** [comment]
I think it has been fixed by https://github.com/natemcmaster/CommandLineUtils/commit/042f4a912d4b5e3f3343ff471b6c42ae1edd05f9

**Comment by natemcmaster** [comment]
Can you try https://www.nuget.org/packages/McMaster.Extensions.CommandLineUtils/4.0.0-beta.74 and see if it fixes the issue?

**Comment by numbworks** [comment]
Hey,

first of all thank you for all the work that has been done to make this library available to us! :)

I think I have the same issue!

Do you spot some error in my *Validator code or should I use the 4.0.0-beta.74 as well to sort it out?
I'm using CommandLineUtils v3.1.0 at the moment.

**My custom Validator class:**

```
using System;
using System.ComponentModel.DataAnnotations;
using McMaster.Extensions.CommandLineUtils;
using McMaster.Extensions.CommandLineUtils.Validation;
using NW.SomeClient.Messages;

namespace NW.SomeClient
{

    public class ThresholdValueValidator : IOptionValidator
    {

        IThresholdValueManager _thresholdValueManager;

        public ThresholdValueValidator(IThresholdValueManager thresholdValueManager) 
        {

            // To-Do: validation

            _thresholdValueManager = thresholdValueManager;

        }

        public ThresholdValueValidator()
            : this(new ThresholdValueManager()) { }

        public ValidationResult GetValidationResult(CommandOption option, ValidationContext context)
        {

            if (_thresholdValueManager.IsValid(option.Value()))
                return ValidationResult.Success;

            return new ValidationResult(MessageCollection.ThresholdValidator_ThresholdValueNotValidFormat.Invoke(option.Value()));

        }

    }
	
}
```

**Program:**

```
class Program
{	

	/* ... */	

	private static CommandOption CreateThresholdValueOption(CommandLineApplication subCommand)
	{

		CommandOption result
			= subCommand
				.Option(Option_ThresholdValue_Template, Option_ThresholdValue_Description, CommandOptionType.SingleValue)
				.IsRequired(false, Option_ThresholdValue_ErrorMessage)
				.Accepts(validator => validator.Use(new ThresholdValueValidator()));

		return result;

	}

	/* ... */

}
```

**Exception:**
	
`Unhandled exception. System.InvalidCastException: Unable to cast object of type 'NW.SomeClient.ThresholdValueValidator' to type 'McMaster.Extensions.CommandLineUtils.Validation.AttributeValidator'.`
	
**Stacktrace:**
	
```
PS C:\Dropbox\Repositories\csharp-nw.Some\NW.Some\src\NW.SomeClient\bin\Debug\netcoreapp3.1> .\NW.SomeClient.exe exploration explore --help

Usage: NW.SomeClient.exe exploration explore [options]

Options:
  --stage                   The depth of an Exploration.
                            Allowed values are: S2, S3.
  --thresholdtype           The exploration proceeds until this criteria is met.
                            Allowed values are: finalpagenumber, thresholddate, jobpostingid.
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'NW.SomeClient.ThresholdValueValidator' to type 'McMaster.Extensions.CommandLineUtils.Validation.AttributeValidator'.
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at McMaster.Extensions.CommandLineUtils.HelpText.DefaultHelpTextGenerator.GenerateOptions(CommandLineApplication application, TextWriter output, IReadOnlyList`1 visibleOptions, Int32 firstColumnWidth)
   at McMaster.Extensions.CommandLineUtils.HelpText.DefaultHelpTextGenerator.GenerateBody(CommandLineApplication application, TextWriter output)
   at McMaster.Extensions.CommandLineUtils.HelpText.DefaultHelpTextGenerator.Generate(CommandLineApplication application, TextWriter output)
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessOption(OptionArgument arg)
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessNext()
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.Process()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Parse(String[] args)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at NW.SomeClient.Program.Main(String[] args) in C:\Dropbox\Repositories\csharp-nw.Some\NW.Some\src\NW.SomeClient\Program.cs:line 90	
```
